version: "3.7"

networks:
  internal:
    name: internal
    driver: overlay
    attachable: true

volumes:
  postgresdatabase: {}
  contracts: {}

services:
  postgresdatabase:
    image: postgres:12
    networks:
      - internal
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: skale
      POSTGRES_PASSWORD: skale
      POSTGRES_DB: skale
    volumes:
      - postgresdatabase:/var/lib/postgresql/data/

  skalemigrate:
    build:
      context: .
      dockerfile: ./Dockerfile.migration
    networks:
      - internal
    environment:
      DATABASE_URL: postgres://skale:skale@skale-indexer_postgresdatabase_1/skale?sslmode=disable
    depends_on:
      - postgresdatabase

  skale:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./test/integration/testFiles:/contracts
    networks:
      - internal
    ports:
      - "8085:8085"
    environment:
      ADDRESS: 0.0.0.0:8085
      DATABASE_URL: postgres://skale:skale@skale-indexer_postgresdatabase_1/skale?sslmode=disable
      ABI_DIR: /contracts
    depends_on:
      - postgresdatabase
      - skalemigrate
